<?php
/**
 * @file
 * Core Lydia features.
 */

/**
 * Implements hook_menu().
 */
function lydia_base_menu() {
  return array(
    // Top level "Lydia" container.
    'admin/lydia' => array(
      'title' => 'Lydia',
      'description' => 'Administration area for Lydia.',
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('access administration pages'),
      'file path' => drupal_get_path('module', 'system'),
      'file' => 'system.admin.inc',
      'weight' => -20,
    ),
  );
}

/**
 * Renders a View for display in some other element.
 *
 * @param $view_key
 *   The ID of the View to embed.
 * @param $display_id
 *   The ID of the display of the View that will actually be rendered.
 * @param $arguments
 *   An array of arguments to pass to the View.
 *
 * @return
 *   The rendered output of the chosen View display.
 */
function lydia_base_embed_view($view_id, $display_id, $arguments = array()) {
  // Load the cart line item View.
  $view = views_get_view($view_id);
  $view->set_display($display_id);

  // Set the specific line items for this order.
  $view->set_arguments($arguments);

  // Prepare and execute the View query.
  $view->pre_execute();
  $view->execute();

  // Return the rendered View.
  return $view->render();
}
